### ISSUE TITLE
Add aria2c downloader

### ISSUE THREAD

**Issue by quivenda** [pouriap/Firefox-DownloadGrab#6]
Hi, thanks for great add-ons.

How to add aria2c downloader to download manager like FlashGot?
In Pale moon I can add manually with this arguments
```md
-x10 -s10 --continue --file-allocation=none [-d FOLDER] [-o FNAME] [--referer=REFERER] [--load-cookies=CFILE] [--input-file=UFILE] [URL]
```
![Qkst0kVc2c](https://user-images.githubusercontent.com/125377517/220247368-b20e34b3-764c-4c2c-9dbd-e571ec4b83ab.png)

I don't know how to add manually to Grabby.

**Comment by pouriap** [comment]
Hi.

Currently this feature is not available in Grabby but comman-line download managers, plus curl and wget, are something I intend to add in the future.

In the meantime I have updated the addon and added the ability to download videos too. I have submitted the new version to Mozilla and it should be signed by them and ready in a matter of days.

**Comment by pouriap** [comment]
The new release is ready https://github.com/pouriap/Grabby/releases/tag/v0.60.0a

**Comment by pouriap** [comment]
This feature was added in version 0.62.12
